# Generated by Django 6.0.7 on 2026-07-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_artist_albumcredit_album_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
