-- Crescendo - core table definitions
--
-- Generated from the live database, so it matches what is actually running.
-- With 001_app_session.sql and 002_artist_uploads.sql this rebuilds the whole
-- schema on an empty PostgreSQL database:
--
--     python manage.py apply_schema
--
-- Order matters. Tables come first, then primary and unique keys, and only
-- then foreign keys - a foreign key cannot reference a column that does not
-- yet carry a unique constraint.
--
-- Every statement is re-runnable, so applying this to a database that already
-- has the tables does nothing at all.
--
-- These definitions originally came from the 40% milestone's ORM migrations,
-- which no longer execute now the project uses raw SQL. This file replaces
-- them as the source of truth.


-- ======================================================================
-- 1. Tables
-- ======================================================================

CREATE TABLE IF NOT EXISTS music_album (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title character varying(255) NOT NULL,
    release_date date NOT NULL,
    cover_url character varying(500) NOT NULL,
    created_by_id bigint
);

CREATE TABLE IF NOT EXISTS music_albumcredit (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role character varying(20) NOT NULL,
    album_id bigint NOT NULL,
    artist_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_artist (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255) NOT NULL,
    bio text NOT NULL,
    verified boolean NOT NULL,
    user_id bigint
);

CREATE TABLE IF NOT EXISTS music_era (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(100) NOT NULL,
    description text
);

CREATE TABLE IF NOT EXISTS music_follow (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    artist_id bigint NOT NULL,
    follower_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_genre (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS music_groupplaylist (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    added_at timestamp with time zone NOT NULL,
    personal_group_id bigint NOT NULL,
    playlist_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_groupreview (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating smallint NOT NULL,
    review_text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    reviewer_id bigint NOT NULL,
    group_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_grouptrack (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    added_at timestamp with time zone NOT NULL,
    personal_group_id bigint NOT NULL,
    track_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_likedtrack (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    track_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_personalgroup (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    is_public boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    owner_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_playhistory (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    played_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    track_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_playlist (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255) NOT NULL,
    is_public boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_playlisttrack (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    position integer NOT NULL,
    added_at timestamp with time zone NOT NULL,
    playlist_id bigint NOT NULL,
    track_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_track (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title character varying(255) NOT NULL,
    duration_sec integer NOT NULL,
    track_number integer NOT NULL,
    album_id bigint NOT NULL,
    era_id bigint,
    genre_id bigint,
    audio_file character varying(500) NOT NULL,
    approval_status character varying(20) DEFAULT 'approved'::character varying NOT NULL,
    submitted_by_id bigint,
    submitted_at timestamp with time zone,
    reviewed_by_id bigint,
    reviewed_at timestamp with time zone,
    review_note character varying(500) DEFAULT ''::character varying NOT NULL
);

CREATE TABLE IF NOT EXISTS music_trackcredit (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role character varying(20) NOT NULL,
    artist_id bigint NOT NULL,
    track_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS music_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    account_type character varying(20) NOT NULL,
    subscription_type character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


-- ======================================================================
-- 2. Primary keys, unique constraints and checks
-- ======================================================================

DO $$ BEGIN
    ALTER TABLE music_album ADD CONSTRAINT music_album_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_albumcredit ADD CONSTRAINT music_albumcredit_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_artist ADD CONSTRAINT music_artist_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_artist ADD CONSTRAINT music_artist_user_id_key UNIQUE (user_id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_era ADD CONSTRAINT music_era_name_key UNIQUE (name);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_era ADD CONSTRAINT music_era_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_follow ADD CONSTRAINT music_follow_follower_id_artist_id_281f117e_uniq UNIQUE (follower_id, artist_id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_follow ADD CONSTRAINT music_follow_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_genre ADD CONSTRAINT music_genre_name_key UNIQUE (name);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_genre ADD CONSTRAINT music_genre_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_groupplaylist ADD CONSTRAINT music_groupplaylist_personal_group_id_playlist_id_ad7bac8a_uniq UNIQUE (personal_group_id, playlist_id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_groupplaylist ADD CONSTRAINT music_groupplaylist_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_groupreview ADD CONSTRAINT music_groupreview_group_id_reviewer_id_4beca12f_uniq UNIQUE (group_id, reviewer_id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_groupreview ADD CONSTRAINT music_groupreview_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_groupreview ADD CONSTRAINT music_groupreview_rating_check CHECK ((rating >= 0));
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_grouptrack ADD CONSTRAINT music_grouptrack_personal_group_id_track_id_615888fd_uniq UNIQUE (personal_group_id, track_id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_grouptrack ADD CONSTRAINT music_grouptrack_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_likedtrack ADD CONSTRAINT music_likedtrack_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_likedtrack ADD CONSTRAINT music_likedtrack_user_id_track_id_6afb53de_uniq UNIQUE (user_id, track_id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_personalgroup ADD CONSTRAINT music_personalgroup_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_playhistory ADD CONSTRAINT music_playhistory_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_playlist ADD CONSTRAINT music_playlist_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_playlisttrack ADD CONSTRAINT music_playlisttrack_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_playlisttrack ADD CONSTRAINT music_playlisttrack_playlist_id_track_id_35f9bc25_uniq UNIQUE (playlist_id, track_id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_playlisttrack ADD CONSTRAINT music_playlisttrack_position_check CHECK (("position" >= 0));
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_track ADD CONSTRAINT music_track_approval_status_check CHECK (((approval_status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[])));
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_track ADD CONSTRAINT music_track_duration_sec_check CHECK ((duration_sec >= 0));
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_track ADD CONSTRAINT music_track_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_track ADD CONSTRAINT music_track_track_number_check CHECK ((track_number >= 0));
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_trackcredit ADD CONSTRAINT music_trackcredit_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_user ADD CONSTRAINT music_user_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_user ADD CONSTRAINT music_user_username_key UNIQUE (username);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;


-- ======================================================================
-- 3. Foreign keys
-- ======================================================================

DO $$ BEGIN
    ALTER TABLE music_album ADD CONSTRAINT music_album_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES music_user(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_albumcredit ADD CONSTRAINT music_albumcredit_album_id_64dbf6e7_fk_music_album_id FOREIGN KEY (album_id) REFERENCES music_album(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_albumcredit ADD CONSTRAINT music_albumcredit_artist_id_0a9af83b_fk_music_artist_id FOREIGN KEY (artist_id) REFERENCES music_artist(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_artist ADD CONSTRAINT music_artist_user_id_b0d56609_fk_music_user_id FOREIGN KEY (user_id) REFERENCES music_user(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_follow ADD CONSTRAINT music_follow_artist_id_a956cb03_fk_music_artist_id FOREIGN KEY (artist_id) REFERENCES music_artist(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_follow ADD CONSTRAINT music_follow_follower_id_467e39d6_fk_music_user_id FOREIGN KEY (follower_id) REFERENCES music_user(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_groupplaylist ADD CONSTRAINT music_groupplaylist_personal_group_id_f90de1c3_fk_music_per FOREIGN KEY (personal_group_id) REFERENCES music_personalgroup(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_groupplaylist ADD CONSTRAINT music_groupplaylist_playlist_id_665fe4ac_fk_music_playlist_id FOREIGN KEY (playlist_id) REFERENCES music_playlist(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_groupreview ADD CONSTRAINT music_groupreview_group_id_38567287_fk_music_personalgroup_id FOREIGN KEY (group_id) REFERENCES music_personalgroup(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_groupreview ADD CONSTRAINT music_groupreview_reviewer_id_e3b2389b_fk_music_user_id FOREIGN KEY (reviewer_id) REFERENCES music_user(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_grouptrack ADD CONSTRAINT music_grouptrack_personal_group_id_f670b9cc_fk_music_per FOREIGN KEY (personal_group_id) REFERENCES music_personalgroup(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_grouptrack ADD CONSTRAINT music_grouptrack_track_id_ba37f5a0_fk_music_track_id FOREIGN KEY (track_id) REFERENCES music_track(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_likedtrack ADD CONSTRAINT music_likedtrack_track_id_02c84249_fk_music_track_id FOREIGN KEY (track_id) REFERENCES music_track(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_likedtrack ADD CONSTRAINT music_likedtrack_user_id_7f7fc9db_fk_music_user_id FOREIGN KEY (user_id) REFERENCES music_user(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_personalgroup ADD CONSTRAINT music_personalgroup_owner_id_ebdd2490_fk_music_user_id FOREIGN KEY (owner_id) REFERENCES music_user(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_playhistory ADD CONSTRAINT music_playhistory_track_id_76b8655e_fk_music_track_id FOREIGN KEY (track_id) REFERENCES music_track(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_playhistory ADD CONSTRAINT music_playhistory_user_id_9e39354f_fk_music_user_id FOREIGN KEY (user_id) REFERENCES music_user(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_playlist ADD CONSTRAINT music_playlist_user_id_c54fe691_fk_music_user_id FOREIGN KEY (user_id) REFERENCES music_user(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_playlisttrack ADD CONSTRAINT music_playlisttrack_playlist_id_585a8ed4_fk_music_playlist_id FOREIGN KEY (playlist_id) REFERENCES music_playlist(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_playlisttrack ADD CONSTRAINT music_playlisttrack_track_id_427b6391_fk_music_track_id FOREIGN KEY (track_id) REFERENCES music_track(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_track ADD CONSTRAINT music_track_album_id_f2264d26_fk_music_album_id FOREIGN KEY (album_id) REFERENCES music_album(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_track ADD CONSTRAINT music_track_era_id_6cc2a841_fk_music_era_id FOREIGN KEY (era_id) REFERENCES music_era(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_track ADD CONSTRAINT music_track_genre_id_427cb441_fk_music_genre_id FOREIGN KEY (genre_id) REFERENCES music_genre(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_track ADD CONSTRAINT music_track_reviewed_by_id_fkey FOREIGN KEY (reviewed_by_id) REFERENCES music_user(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_track ADD CONSTRAINT music_track_submitted_by_id_fkey FOREIGN KEY (submitted_by_id) REFERENCES music_user(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_trackcredit ADD CONSTRAINT music_trackcredit_artist_id_310a0fa8_fk_music_artist_id FOREIGN KEY (artist_id) REFERENCES music_artist(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE music_trackcredit ADD CONSTRAINT music_trackcredit_track_id_3be46fbc_fk_music_track_id FOREIGN KEY (track_id) REFERENCES music_track(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;


-- ======================================================================
-- 4. Indexes
-- ======================================================================

CREATE INDEX IF NOT EXISTS music_album_created_by_idx ON music_album USING btree (created_by_id);

CREATE INDEX IF NOT EXISTS music_albumcredit_album_id_64dbf6e7 ON music_albumcredit USING btree (album_id);

CREATE INDEX IF NOT EXISTS music_albumcredit_artist_id_0a9af83b ON music_albumcredit USING btree (artist_id);

CREATE INDEX IF NOT EXISTS music_era_name_c8a894ea_like ON music_era USING btree (name varchar_pattern_ops);

CREATE INDEX IF NOT EXISTS music_follow_artist_id_a956cb03 ON music_follow USING btree (artist_id);

CREATE INDEX IF NOT EXISTS music_follow_follower_id_467e39d6 ON music_follow USING btree (follower_id);

CREATE INDEX IF NOT EXISTS music_genre_name_e0563592_like ON music_genre USING btree (name varchar_pattern_ops);

CREATE INDEX IF NOT EXISTS music_groupplaylist_personal_group_id_f90de1c3 ON music_groupplaylist USING btree (personal_group_id);

CREATE INDEX IF NOT EXISTS music_groupplaylist_playlist_id_665fe4ac ON music_groupplaylist USING btree (playlist_id);

CREATE INDEX IF NOT EXISTS music_groupreview_group_id_38567287 ON music_groupreview USING btree (group_id);

CREATE INDEX IF NOT EXISTS music_groupreview_reviewer_id_e3b2389b ON music_groupreview USING btree (reviewer_id);

CREATE INDEX IF NOT EXISTS music_grouptrack_personal_group_id_f670b9cc ON music_grouptrack USING btree (personal_group_id);

CREATE INDEX IF NOT EXISTS music_grouptrack_track_id_ba37f5a0 ON music_grouptrack USING btree (track_id);

CREATE INDEX IF NOT EXISTS music_likedtrack_track_id_02c84249 ON music_likedtrack USING btree (track_id);

CREATE INDEX IF NOT EXISTS music_likedtrack_user_id_7f7fc9db ON music_likedtrack USING btree (user_id);

CREATE INDEX IF NOT EXISTS music_personalgroup_owner_id_ebdd2490 ON music_personalgroup USING btree (owner_id);

CREATE INDEX IF NOT EXISTS music_playhistory_track_id_76b8655e ON music_playhistory USING btree (track_id);

CREATE INDEX IF NOT EXISTS music_playhistory_user_id_9e39354f ON music_playhistory USING btree (user_id);

CREATE INDEX IF NOT EXISTS music_playlist_user_id_c54fe691 ON music_playlist USING btree (user_id);

CREATE INDEX IF NOT EXISTS music_playlisttrack_playlist_id_585a8ed4 ON music_playlisttrack USING btree (playlist_id);

CREATE INDEX IF NOT EXISTS music_playlisttrack_track_id_427b6391 ON music_playlisttrack USING btree (track_id);

CREATE INDEX IF NOT EXISTS music_track_album_id_f2264d26 ON music_track USING btree (album_id);

CREATE INDEX IF NOT EXISTS music_track_approval_status_idx ON music_track USING btree (approval_status);

CREATE INDEX IF NOT EXISTS music_track_era_id_6cc2a841 ON music_track USING btree (era_id);

CREATE INDEX IF NOT EXISTS music_track_genre_id_427cb441 ON music_track USING btree (genre_id);

CREATE INDEX IF NOT EXISTS music_track_submitted_by_idx ON music_track USING btree (submitted_by_id);

CREATE INDEX IF NOT EXISTS music_trackcredit_artist_id_310a0fa8 ON music_trackcredit USING btree (artist_id);

CREATE INDEX IF NOT EXISTS music_trackcredit_track_id_3be46fbc ON music_trackcredit USING btree (track_id);

CREATE INDEX IF NOT EXISTS music_user_username_c4fd7f70_like ON music_user USING btree (username varchar_pattern_ops);
